INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FIELD_STOP_DIAMETER,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (1,'LUMINOS 12 mm',2,82,2,12,15,7,7);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FIELD_STOP_DIAMETER,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (2,'LUMINOS 15 mm',2,82,2,17,26,15,7);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FIELD_STOP_DIAMETER,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (3,'LUMINOS 19 mm',2,82,3,20,30,19,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FIELD_STOP_DIAMETER,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (4,'LUMINOS 23 mm',2,82,3,20,37,23,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FIELD_STOP_DIAMETER,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (5,'LUMINOS 31 mm',2,82,3,27,47,31,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (6,'OMNI 4 mm',2,50,2,6,4,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (7,'OMNI 6 mm',2,50,2,5,6,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (8,'OMNI 9 mm',2,50,2,6,9,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (9,'OMNI 12 mm',2,50,2,8,12,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (10,'OMNI 15 mm',2,50,2,13,15,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (11,'OMNI 32 mm',2,44,2,22,32,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (12,'OMNI 40 mm',2,43,2,31,40,4);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (13,'X-Cel LX 2.3 mm',2,60,2,16,2.3,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (14,'X-Cel LX 5 mm',2,60,2,16,5,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (15,'X-Cel LX 7 mm',2,60,2,16,7,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (16,'X-Cel LX 9 mm',2,60,2,16,9,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (17,'X-Cel LX 12 mm',2,60,2,16,12,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (18,'X-Cel LX 18 mm',2,60,2,16,18,6);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (19,'X-Cel LX 25 mm',2,60,2,16,25,6);

INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (21,'Ramsden SR 4 mm',2,28,1,3,4,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (22,'Ramsden SR 4 mm',2,28,2,3,4,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (23,'Ramsden F 6 mm',2,28,1,3,6,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (24,'Ramsden F 6 mm',2,28,2,3,6,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (25,'Huygens H 8 mm',2,30,1,5,8,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (26,'Huygens H 8 mm',2,30,2,5,8,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (27,'Huygens H 12.5 mm',2,30,1,8,12.5,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (28,'Huygens H 12.5 mm',2,30,2,8,12.5,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (29,'Huygens H 20 mm',2,32,1,8,20,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (30,'Huygens H 20 mm',2,32,2,8,20,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (31,'Huygens HM 25 mm',2,32,1,10,25,2);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (32,'Huygens HM 25 mm',2,32,2,10,25,2);

INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (33,'Kellner Achromatic SMA 6 mm',2,52,1,4,6,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (34,'Kellner Achromatic SMA 6 mm',2,52,2,4,6,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (35,'Kellner Achromatic SMA 10 mm',2,52,1,6,10,3);
INSERT INTO EYEPIECE(ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (36,'Kellner Achromatic SMA 10 mm',2,52,2,6,10,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (37,'Kellner Achromatic SMA 12 mm',2,52,1,7,12,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (38,'Kellner Achromatic SMA 12 mm',2,52,2,7,12,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (39,'Kellner Achromatic SMA 17 mm',2,52,1,13,17,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (40,'Kellner Achromatic SMA 17 mm',2,52,2,13,17,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (41,'Kellner Achromatic SMA 25 mm',2,52,1,14,25,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (42,'Kellner Achromatic SMA 25 mm',2,52,2,14,25,3);
INSERT INTO EYEPIECE (ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (43,'Kellner Achromatic SMA 9 mm',2,52,1,6,9,3);
INSERT INTO EYEPIECE(ID,NAME,BRANDID,APPARENT_FIELD_OF_VIEW,BARREL_ID,EYE_RELIEF,FOCAL_LENGTH,LENS_ELEMENTS)
        VALUES   (44,'Kellner Achromatic SMA 9 mm',2,52,2,6,9,3);
