DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS MANUFACTURER;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS BARREL;


CREATE TABLE USERS
(
ID INTEGER NOT NULL,
NAME CHAR(25),
EMAIL CHAR(25),
PRIMARY KEY (ID)) ;

CREATE TABLE BRAND
(
ID INTEGER NOT NULL,
MANUFACTURERID INTEGER NOT NULL,
NAME CHAR(25),
PRIMARY KEY (ID)) ;

CREATE TABLE MANUFACTURER
(
ID INTEGER NOT NULL,
ADDRESSID INTEGER NOT NULL,
NAME CHAR(25),
PRIMARY KEY (ID)) ;

CREATE TABLE ADDRESS
(
ID INTEGER NOT NULL,
COUNTRY CHAR(64),
CITY CHAR(64),
STREET CHAR(64),
HOUSE CHAR(64),
ZIP CHAR(10),
PHONE CHAR(20),
EMAIL CHAR(64),
WEB CHAR(64),
LATITUDE DECIMAL,
LONGITUDE DECIMAL,
PRIMARY KEY (ID)) ;

CREATE TABLE PRODUCT
(
ID INTEGER NOT NULL,
BRANDID INTEGER,
NAME CHAR(256),
TIMAGE CHAR(128),
FOLDER CHAR(128),
DESCRIPTION LONGVARCHAR,
PRIMARY KEY (ID)) ;

CREATE TABLE IMAGE
(
ID INTEGER NOT NULL,
PRODUCTID INTEGER NOT NULL,
NAME CHAR(128),
DESCRIPTION LONGVARCHAR,
SCOPE BOOLEAN,
PRIMARY KEY (ID)) ;


CREATE TABLE DISTRIBUTOR
(
ID INTEGER NOT NULL,
ADDRESSID INTEGER NOT NULL,
NAME CHAR(25),
PRIMARY KEY (ID)) ;

CREATE TABLE CURRENCY
(
ID INTEGER NOT NULL,
NAME CHAR(25),
SHORTNAME CHAR(3),
PRIMARY KEY (ID)) ;

CREATE TABLE PRICE
(
ID INTEGER NOT NULL,
PRODUCTID INTEGER NOT NULL,
DISTRIBUTORID INTEGER NOT NULL,
CURRENCYID INTEGER NOT NULL,
PRICE DECIMAL NOT NULL,
PRIMARY KEY (ID)) ;

CREATE TABLE OPTICALSYSTEM
(
ID INTEGER NOT NULL,
NAME CHAR(64),
PRIMARY KEY (ID)) ;

CREATE TABLE MOUNTTYPE
(
ID INTEGER NOT NULL,
NAME CHAR(64),
PRIMARY KEY (ID)) ;

CREATE TABLE CONTROL
(
ID INTEGER NOT NULL,
NAME CHAR(64),
PRIMARY KEY (ID)) ;

CREATE TABLE MOUNT
(
ID INTEGER NOT NULL,
MOUNTTYPEID INTEGER NOT NULL,
CONTROLID INTEGER NOT NULL,
NAME CHAR(64),
PRIMARY KEY (ID)) ;

CREATE TABLE EYEPIECE
(
ID INTEGER NOT NULL,
NAME CHAR(64),
BRANDID INTEGER,
FIELD_STOP_DIAMETER DECIMAL,
APPARENT_FIELD_OF_VIEW DECIMAL,
BARREL_ID INTEGER,
EYE_RELIEF DECIMAL,
LENS_ELEMENTS INTEGER,
FOCAL_LENGTH DECIMAL NOT NULL,
PRIMARY KEY (ID)) ;

CREATE TABLE EYEPIECE_TELESCOPE
(
ID_EYEPIECE INTEGER NOT NULL,
ID_TELESCOPE INTEGER NOT NULL,
PRIMARY KEY (ID_EYEPIECE,ID_TELESCOPE)) ;


CREATE TABLE SITE
(
ID INTEGER NOT NULL,
NAME CHAR(64) NOT NULL,
ADDRESSID CHAR(64) NOT NULL,
PRIMARY KEY (ID)) ;

CREATE TABLE PRODUCTSTAT
(
ID INTEGER NOT NULL,
PRODUCTID INTEGER NOT NULL,
VIEWS INTEGER NOT NULL,
PRIMARY KEY (ID)) ;

CREATE TABLE TELESCOPE
(
ID INTEGER NOT NULL,
TITLE CHAR(64) NOT NULL,
NAME CHAR(64) NOT NULL,
PRODUCTID INTEGER,
SITEID INTEGER,
WEB CHAR(128) NOT NULL,
OPTICALSYSTEMID INTEGER,
MOUNTID INTEGER,
APERTURE DECIMAL NOT NULL,
FOCUS DECIMAL,
WEIGHT DECIMAL,
BARREL_ID INTEGER,
PRIMARY KEY (ID)) ;

CREATE TABLE BARREL
(
ID INTEGER NOT NULL,
NAME CHAR(64) NOT NULL,
DIAMETER_MM DECIMAL,
DIAMETER_INCH DECIMAL,
PRIMARY KEY (ID)) ;
