package info.telescopeworld.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "eyepiece")
public class Eyepiece {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  @ManyToOne
  @JoinColumn(name="brandid")
  private Brand brand;

  private String name;

  @Column(name="APPARENT_FIELD_OF_VIEW")
  private Double apparentFieldOfView;

  @ManyToOne
  @JoinColumn(name="barrel_id")
  private Barrel barrel;

  @Column(name="EYE_RELIEF")
  private Double eyeRelief;

  @Column(name="FOCAL_LENGTH")
  private Double focalLength;

  @Column(name="FIELD_STOP_DIAMETER")
  private Double fieldStopDiameter;

  @Column(name="LENS_ELEMENTS")
  private int lensElements;

  public Eyepiece() { }

  public Eyepiece(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Brand getBrand() {
    return brand;
  }

  public void setBrand(Brand brand) {
    this.brand = brand;
  }

  public Double getApparentFieldOfView() {
    return apparentFieldOfView;
  }

  public void setApparentFieldOfView(Double apparentFieldOfView) {
    this.apparentFieldOfView = apparentFieldOfView;
  }

  public Barrel getBarrel() {
    return barrel;
  }

  public void setBarrel(Barrel barrel) {
    this.barrel = barrel;
  }

  public Double getEyeRelief() {
    return eyeRelief;
  }

  public void setEyeRelief(Double eyeRelief) {
    this.eyeRelief = eyeRelief;
  }

  public Double getFocalLength() {
    return focalLength;
  }

  public void setFocalLength(Double focalLength) {
    this.focalLength = focalLength;
  }

  public int getLensElements() {
    return lensElements;
  }

  public void setLensElements(int lensElements) {
    this.lensElements = lensElements;
  }

  public Double getFieldStopDiameter() {
    return fieldStopDiameter;
  }

  public void setFieldStopDiameter(Double fieldStopDiameter) {
    this.fieldStopDiameter = fieldStopDiameter;
  }
}
