package info.telescopeworld.models;

import javax.persistence.*;

@Entity
@Table(name = "mount")
public class Mount {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  private String name;

  @ManyToOne
  @JoinColumn(name="mounttypeid")
  private MountType mountType;

  @ManyToOne
  @JoinColumn(name="controlid")
  private Control control;

  public Mount() { }

  public Mount(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MountType getMountType() {
    return mountType;
  }

  public void setMountType(MountType mountType) {
    this.mountType = mountType;
  }

  public Control getControl() {
    return control;
  }

  public void setControl(Control control) {
    this.control = control;
  }
}
