package info.telescopeworld.models;

import javax.persistence.*;
import java.util.Set;

@Entity
@Table(name = "telescope")
public class Telescope {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  private String title;

  private String name;

  @OneToOne
  @JoinColumn(name="productid")
  private Product product;

  @ManyToOne
  @JoinColumn(name="siteid")
  private Site site;

  @ManyToOne
  @JoinColumn(name="opticalsystemid")
  private OpticalSystem opticalSystem;

  @ManyToOne
  @JoinColumn(name="mountidid")
  private Mount mount;

  @ManyToMany(cascade = { CascadeType.ALL })
  @JoinTable(
          name = "EYEPIECE_TELESCOPE",
          joinColumns = { @JoinColumn(name = "ID_TELESCOPE") },
          inverseJoinColumns = { @JoinColumn(name = "ID_EYEPIECE") })
  Set<Eyepiece> eyepieces;

  private String web;

  private Double aperture;

  private Double focus;

  private Double weight;

  @ManyToOne
  @JoinColumn(name="barrel_id")
  private Barrel barrel;

  public Telescope() { }

  public Telescope(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public Site getSite() {
    return site;
  }

  public void setSite(Site site) {
    this.site = site;
  }

  public OpticalSystem getOpticalSystem() {
    return opticalSystem;
  }

  public void setOpticalSystem(OpticalSystem opticalSystem) {
    this.opticalSystem = opticalSystem;
  }

  public Mount getMount() {
    return mount;
  }

  public void setMount(Mount mount) {
    this.mount = mount;
  }

  public Double getAperture() {
    return aperture;
  }

  public void setAperture(Double aperture) {
    this.aperture = aperture;
  }

  public Double getFocus() {
    return focus;
  }

  public void setFocus(Double focus) {
    this.focus = focus;
  }

  public Double getWeight() {
    return weight;
  }

  public void setWeight(Double weight) {
    this.weight = weight;
  }

  public Barrel getBarrel() {
    return barrel;
  }

  public void setBarrel(Barrel barrel) {
    this.barrel = barrel;
  }

  public String getTitle() { return title; }

  public void setTitle(String title) { this.title = title; }

  public String getWeb() { return web; }

  public void setWeb(String web) { this.web = web; }

  public Set<Eyepiece> getEyepieces() {
    return eyepieces;
  }

  public void setEyepieces(Set<Eyepiece> eyepieces) {
    this.eyepieces = eyepieces;
  }
}

